// Generated by gencpp from file agile_grasp/FindGraspsResponse.msg
// DO NOT EDIT!


#ifndef AGILE_GRASP_MESSAGE_FINDGRASPSRESPONSE_H
#define AGILE_GRASP_MESSAGE_FINDGRASPSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <agile_grasp/Grasp.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>

namespace agile_grasp
{
template <class ContainerAllocator>
struct FindGraspsResponse_
{
  typedef FindGraspsResponse_<ContainerAllocator> Type;

  FindGraspsResponse_()
    : grasps()
    , grasp_poses()
    , approach_poses()  {
    }
  FindGraspsResponse_(const ContainerAllocator& _alloc)
    : grasps(_alloc)
    , grasp_poses(_alloc)
    , approach_poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::agile_grasp::Grasp_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::agile_grasp::Grasp_<ContainerAllocator> >::other >  _grasps_type;
  _grasps_type grasps;

   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _grasp_poses_type;
  _grasp_poses_type grasp_poses;

   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _approach_poses_type;
  _approach_poses_type approach_poses;





  typedef boost::shared_ptr< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FindGraspsResponse_

typedef ::agile_grasp::FindGraspsResponse_<std::allocator<void> > FindGraspsResponse;

typedef boost::shared_ptr< ::agile_grasp::FindGraspsResponse > FindGraspsResponsePtr;
typedef boost::shared_ptr< ::agile_grasp::FindGraspsResponse const> FindGraspsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agile_grasp::FindGraspsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agile_grasp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'agile_grasp': ['/home/sphero/code/FrankaGrasp/src/agile_grasp/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f075248670dd30604cea28fd03da384";
  }

  static const char* value(const ::agile_grasp::FindGraspsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f075248670dd306ULL;
  static const uint64_t static_value2 = 0x04cea28fd03da384ULL;
};

template<class ContainerAllocator>
struct DataType< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agile_grasp/FindGraspsResponse";
  }

  static const char* value(const ::agile_grasp::FindGraspsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agile_grasp/Grasp[] grasps\n\
geometry_msgs/PoseStamped[] grasp_poses\n\
geometry_msgs/PoseStamped[] approach_poses\n\
\n\
\n\
\n\
================================================================================\n\
MSG: agile_grasp/Grasp\n\
geometry_msgs/Vector3 center\n\
geometry_msgs/Vector3 axis\n\
geometry_msgs/Vector3 approach\n\
geometry_msgs/Vector3 surface_center\n\
std_msgs/Float32 width\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::agile_grasp::FindGraspsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grasps);
      stream.next(m.grasp_poses);
      stream.next(m.approach_poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindGraspsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agile_grasp::FindGraspsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agile_grasp::FindGraspsResponse_<ContainerAllocator>& v)
  {
    s << indent << "grasps[]" << std::endl;
    for (size_t i = 0; i < v.grasps.size(); ++i)
    {
      s << indent << "  grasps[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::agile_grasp::Grasp_<ContainerAllocator> >::stream(s, indent + "    ", v.grasps[i]);
    }
    s << indent << "grasp_poses[]" << std::endl;
    for (size_t i = 0; i < v.grasp_poses.size(); ++i)
    {
      s << indent << "  grasp_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.grasp_poses[i]);
    }
    s << indent << "approach_poses[]" << std::endl;
    for (size_t i = 0; i < v.approach_poses.size(); ++i)
    {
      s << indent << "  approach_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.approach_poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGILE_GRASP_MESSAGE_FINDGRASPSRESPONSE_H
