// Generated by gencpp from file agile_grasp/FindGrasps.msg
// DO NOT EDIT!


#ifndef AGILE_GRASP_MESSAGE_FINDGRASPS_H
#define AGILE_GRASP_MESSAGE_FINDGRASPS_H

#include <ros/service_traits.h>


#include <agile_grasp/FindGraspsRequest.h>
#include <agile_grasp/FindGraspsResponse.h>


namespace agile_grasp
{

struct FindGrasps
{

typedef FindGraspsRequest Request;
typedef FindGraspsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindGrasps
} // namespace agile_grasp


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agile_grasp::FindGrasps > {
  static const char* value()
  {
    return "3e976888ec7075e7e22c71cd9a0d3700";
  }

  static const char* value(const ::agile_grasp::FindGrasps&) { return value(); }
};

template<>
struct DataType< ::agile_grasp::FindGrasps > {
  static const char* value()
  {
    return "agile_grasp/FindGrasps";
  }

  static const char* value(const ::agile_grasp::FindGrasps&) { return value(); }
};


// service_traits::MD5Sum< ::agile_grasp::FindGraspsRequest> should match 
// service_traits::MD5Sum< ::agile_grasp::FindGrasps > 
template<>
struct MD5Sum< ::agile_grasp::FindGraspsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agile_grasp::FindGrasps >::value();
  }
  static const char* value(const ::agile_grasp::FindGraspsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agile_grasp::FindGraspsRequest> should match 
// service_traits::DataType< ::agile_grasp::FindGrasps > 
template<>
struct DataType< ::agile_grasp::FindGraspsRequest>
{
  static const char* value()
  {
    return DataType< ::agile_grasp::FindGrasps >::value();
  }
  static const char* value(const ::agile_grasp::FindGraspsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agile_grasp::FindGraspsResponse> should match 
// service_traits::MD5Sum< ::agile_grasp::FindGrasps > 
template<>
struct MD5Sum< ::agile_grasp::FindGraspsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agile_grasp::FindGrasps >::value();
  }
  static const char* value(const ::agile_grasp::FindGraspsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agile_grasp::FindGraspsResponse> should match 
// service_traits::DataType< ::agile_grasp::FindGrasps > 
template<>
struct DataType< ::agile_grasp::FindGraspsResponse>
{
  static const char* value()
  {
    return DataType< ::agile_grasp::FindGrasps >::value();
  }
  static const char* value(const ::agile_grasp::FindGraspsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGILE_GRASP_MESSAGE_FINDGRASPS_H
